name: vcard
description: A dart port of vCard JS by Eric J Nesser. Create vCards to import contacts into Outlook, iOS, Mac OS, and Android devices from your website or mobile application.
version: 0.2.0
homepage: https://github.com/valerycolong/vcard

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  validators: ^3.0.0
  path: ^1.8.0
  intl: ^0.17.0
  meta: ^1.7.0

dev_dependencies:
  test: any

